/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conference;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        Application classUnderTest = new Application();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
